spring.application.name=web-socket

spring.datasource.url=jdbc:mysql://localhost:3306/otdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Pintu@1617
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jackson.serialization.fail-on-empty-beans=false

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=simple

file.upload-dir=uploads

# Sign up free at https://cloudinary.com ? Dashboard ? copy these 3 values
cloudinary.cloud-name=dm4bes8hg
cloudinary.api-key=341687998735241
cloudinary.api-secret=TdFuwZN4oLSvge6nFH_uh2DiRpk
jwt.secret=asdfghjklqwertyuiopzxcvbnmrdyhjgdfqwertyuiasdfghjklqwertyuiopzxcvbnmrdyhjgdfqwertyuiasdfghjklqwertyuiopzxcvbnmrdyhjgdfqwertyui